import React,{useEffect,useRef,useState} from 'react';
import {useScroll,useMotionValueEvent,useReducedMotion} from 'motion/react';
import {asset} from '../site';
export default function HeroFilm({en}){
 const root=useRef(null),canvas=useRef(null),engine=useRef(null);const reduce=useReducedMotion();const [ready,setReady]=useState(false);
 const {scrollYProgress}=useScroll({target:root,offset:['start start','end end']});
 useEffect(()=>{if(reduce||navigator.connection?.saveData){root.current.classList.add('reduced');return;}let disposed=false,manifest,wanted=0,last=-1,hasDrawn=false;const cache=new Map(),inflight=new Map(),attempts=new Map();const ctx=canvas.current.getContext('2d');
 const draw=()=>{if(disposed||!manifest||!cache.size)return;let index=wanted;if(!cache.has(index))index=[...cache.keys()].reduce((a,b)=>Math.abs(a-wanted)<Math.abs(b-wanted)?a:b);const frame=cache.get(index),cv=canvas.current;const sourceRatio=Math.min(manifest.width/cv.clientWidth,manifest.height/cv.clientHeight),ratio=Math.max(.5,Math.min(devicePixelRatio||1,sourceRatio)),w=Math.round(cv.clientWidth*ratio),h=Math.round(cv.clientHeight*ratio);if(cv.width!==w||cv.height!==h){cv.width=w;cv.height=h;}ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);const mobile=w/h<.8,fit=Math.max(w/frame.width,h/frame.height),progress=index/(manifest.count-1),settle=Math.min(1,Math.max(0,(progress-.5)/.35)),scale=mobile?fit*(1-settle*.56):fit,fw=frame.width*scale,fh=frame.height*scale;ctx.drawImage(frame,(w-fw)/2,(h-fh)/2,fw,fh);if(mobile&&fh<h){const top=(h-fh)/2,bottom=top+fh,fade=Math.min(fh*.14,65*ratio);const upper=ctx.createLinearGradient(0,top,0,top+fade);upper.addColorStop(0,'#fff');upper.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=upper;ctx.fillRect(0,top,w,fade);const lower=ctx.createLinearGradient(0,bottom-fade,0,bottom);lower.addColorStop(0,'rgba(255,255,255,0)');lower.addColorStop(1,'#fff');ctx.fillStyle=lower;ctx.fillRect(0,bottom-fade,w,fade);}cv.dataset.frame=String(index);if(!hasDrawn){hasDrawn=true;setReady(true);}};
 const pump=()=>{if(disposed||!manifest)return;for(const [i,b] of cache)if(Math.abs(i-wanted)>12){b.close();cache.delete(i);}for(const [i,c] of inflight)if(Math.abs(i-wanted)>12)c.abort();const candidates=[wanted];for(let d=1;d<=6;d++)candidates.push(wanted+d,wanted-d);for(const i of candidates){if(inflight.size>=4)break;if(i<0||i>=manifest.count||cache.has(i)||inflight.has(i)||(attempts.get(i)||0)>=2)continue;const controller=new AbortController();inflight.set(i,controller);attempts.set(i,(attempts.get(i)||0)+1);fetch(asset(manifest.pattern.replace('{index}',String(i).padStart(4,'0'))),{signal:controller.signal}).then(r=>{if(!r.ok)throw Error('frame');return r.blob();}).then(createImageBitmap).then(b=>{if(disposed||Math.abs(i-wanted)>12)b.close();else{attempts.delete(i);cache.set(i,b);draw();}}).catch(e=>{if(e.name==='AbortError')attempts.set(i,Math.max(0,(attempts.get(i)||1)-1));else if(i===wanted&&!cache.size&&(attempts.get(i)||0)>=2)root.current?.classList.add('reduced');}).finally(()=>{inflight.delete(i);pump();});}};
 const update=p=>{if(!manifest)return;const t=p<.08?0:p>.94?1:(p-.08)/.86;wanted=Math.round(t*(manifest.count-1));if(last!==wanted){last=wanted;draw();pump();}};engine.current={update};fetch(asset(matchMedia('(max-width:600px)').matches?'media/sequence-mobile.json':'media/sequence.json')).then(r=>{if(!r.ok)throw Error('sequence');return r.json();}).then(m=>{manifest=m;update(scrollYProgress.get());}).catch(()=>root.current?.classList.add('reduced'));const resize=new ResizeObserver(draw);resize.observe(canvas.current);return()=>{disposed=true;resize.disconnect();inflight.forEach(c=>c.abort());cache.forEach(b=>b.close());engine.current=null;};},[reduce]);
 useMotionValueEvent(scrollYProgress,'change',p=>{engine.current?.update(p);root.current?.style.setProperty('--hint',p<.12?'1':'0');root.current?.style.setProperty('--copy',String(Math.max(0,1-p/.28)));});
 return <section id="inicio" className={`film ${reduce?'reduced':''}`} ref={root} aria-label={en?'Claudia in a white studio':'Claudia en un estudio blanco'}><div className="film-stage"><img className="film-poster" src={asset('media/hero.webp?v=2')} width="1920" height="1080" alt={en?'Claudia Rivas seated in a navy suit':'Claudia Rivas sentada con traje azul marino'} fetchPriority="high"/><canvas ref={canvas} className={ready?'ready':''} aria-hidden="true"/><div className="film-fade"/><div className="film-copy"><p>{en?'Entrepreneur · Model · Host':'Empresaria · Modelo · Host'}</p><h1>Claudia Rivas.<br/><span>{en?'Vision in motion.':'Visión en movimiento.'}</span></h1></div><div className="scroll-cue">{en?'Scroll to meet me':'Desliza para conocerme'}<span aria-hidden="true">↓</span></div><a className="skip" href="#sobre-mi">{en?'Skip introduction':'Saltar introducción'} ↗</a></div></section>;
}





