import React from 'react';
import {content as es} from './content/es';
import {content as english} from './content/en';
import {asset,email} from './site';
import HeroFilm from './components/HeroFilm';
import {Header,FloatingActions} from './components/Navigation';
import CollectionSurfer from './components/ui/collection-surfer';
import PodcastSection from './components/PodcastSection';
import ContactForm from './components/ContactForm';
import AnalyticsConsent from './components/AnalyticsConsent';
import SiteFooter from './components/SiteFooter';
import LegalPage from './components/LegalPage';
const Arrow=()=> <span aria-hidden="true">↗</span>;
function Link({href='#contacto',children}){return <a className="text-link" href={href}>{children}<Arrow/></a>;}
function Photo({name,alt}){return <div className="photo"><img loading="lazy" src={asset(`media/${name}.webp`)} srcSet={`${asset(`media/${name}-480.webp`)} 480w, ${asset(`media/${name}-960.webp`)} 960w`} sizes="(max-width:600px) 86vw, 42vw" width="960" height="1200" alt={alt}/></div>;}
export default function App({lang='es',page='home'}){const en=lang==='en',c=en?english:es,t=(a,b)=>en?b:a;if(page!=='home')return <LegalPage en={en} type={page}/>;return <><a className="a11y-skip" href="#sobre-mi">{t('Ir al contenido','Skip to content')}</a><Header en={en}/><main><HeroFilm en={en}/><section className="intro section" id="sobre-mi" tabIndex="-1"><p className="eyebrow">Claudia Rivas · Miami</p><h2 className="intro-title">{t('Visión empresarial.','Business vision.')}<br/><span>{t('Presencia propia.','Distinct presence.')}</span></h2><p className="intro-copy">{c.intro}</p><Link href="#trayectoria">{t('Conoce mi universo','Explore my world')}</Link><div className="about-row"><Photo name="portrait" alt={t('Claudia Rivas sentada con traje negro','Claudia Rivas seated in a black suit')}/><div className="about-copy"><p className="small-label">{t('Una misma esencia.','The same essence.')}</p><h2>{t('Muchas facetas.','Many facets.')}<br/>{t('Una sola Claudia.','One Claudia.')}</h2><p>{c.about}</p><p>{t('Escuchar, observar y conectar. Esa mirada está presente en cada proyecto que emprendo.','Listening, observing and connecting. That perspective shapes every project I undertake.')}</p></div></div></section>
<section className="business section" id="trayectoria" tabIndex="-1"><div className="business-heading"><p className="eyebrow">Enterprises Business Corp</p><h2>{t('Las oportunidades','Opportunities')}<br/>{t('empiezan con visión.','begin with vision.')}</h2></div><div className="business-grid"><div className="business-copy"><p className="small-label">{t('CEO & empresaria','CEO & entrepreneur')}</p><p>{c.business}</p><Link>{t('Hablemos','Let’s talk')}</Link><br/><Link href="https://www.instagram.com/enterprisesbusinesscorp/">{t('La empresa en Instagram','The company on Instagram')}</Link><div className="business-notes">{(en?['Technology','Wholesale','Business development']:['Tecnología','Comercio mayorista','Desarrollo de negocios']).map(x=><span key={x}>{x}</span>)}</div></div><Photo name="business" alt={t('Claudia Rivas en su actividad empresarial de telefonía','Claudia Rivas in her mobile phone business')}/></div></section>
<section id="claud-360" className="show section" tabIndex="-1"><div className="show-title">Claud <span>360<sup>°</sup></span></div><h2>{t('Una buena conversación','A good conversation')}<br/>{t('puede abrir un mundo.','can open up a world.')}</h2><p>{c.show}</p><PodcastSection en={en}/><div className="show-bottom"><div className="topics">{c.topics.map(x=><span key={x}>{x}</span>)}</div><Link>{t('Proponer un invitado','Suggest a guest')}</Link></div></section>
<section className="fashion" id="moda" tabIndex="-1"><div className="fashion-heading section"><h2>{t('La imagen también','Image has')}<br/>{t('tiene voz.','a voice, too.')}</h2><p>{c.fashion}</p></div><CollectionSurfer en={en}/></section>
<section id="colaboraciones" className="collaborations section"><p className="eyebrow">{t('Hagamos algo juntos','Let’s create something together')}</p><h2>{t('Tu próxima idea.','Your next idea.')}<br/>{t('Nuestra próxima conversación.','Our next conversation.')}</h2><div className="collab-list">{(en?[['Brands & businesses','Campaigns, partnerships and projects with a shared vision.'],['Media & Claud 360','Interviews, stories and new perspectives.'],['Fashion & events','Runways, brand image and professional appearances.']]:[['Marcas & empresas','Campañas, alianzas y proyectos con una visión compartida.'],['Medios & Claud 360','Entrevistas, historias y nuevas perspectivas.'],['Moda & eventos','Pasarelas, imagen de marca y participaciones profesionales.']]).map(([title,body])=><a href="#contacto" key={title}><h3>{title}</h3><p>{body}</p><Arrow/></a>)}</div></section>
<section className="faq section" id="preguntas"><h2>{t('Un poco más sobre mí.','A little more about me.')}</h2><div>{c.faq.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>
<section className="contact section" id="contacto" tabIndex="-1"><p className="eyebrow">{t('Desde Miami, abierta al mundo','From Miami, open to the world')}</p><h2>{t('Hablemos.','Let’s talk.')}</h2><p>{t('Entrevistas, colaboraciones o una idea que merece tomar forma. Me encantará conocer tu propuesta.','Interviews, collaborations or an idea worth bringing to life. I’d love to hear your proposal.')}</p><a className="contact-email" href={`mailto:${email}`}>{email} ↗</a><ContactForm en={en}/></section>
<section className="privacy section" id="privacidad" tabIndex="-1"><p className="eyebrow">{t('Privacidad','Privacy')}</p><h2>{t('Tus datos, con claridad.','Your data, clearly handled.')}</h2><div className="privacy-grid"><p>{t(`Este sitio utiliza Google Analytics únicamente si lo autorizas. La medición nos ayuda a conocer visitas, navegación e interacción para mejorar la experiencia. No enviamos a Google datos que permitan identificarte directamente.`, `This site uses Google Analytics only with your permission. Measurement helps us understand visits, navigation and interaction so we can improve the experience. We do not send Google information that directly identifies you.`)}</p><p>{t(`Puedes rechazar la medición sin perder ninguna función de la web. Para retirar un consentimiento anterior, elimina los datos de este sitio en tu navegador. Para ejercer tus derechos de acceso, rectificación o supresión, escribe a ${email}.`, `You can reject measurement without losing any website feature. To withdraw a previous choice, clear this site's data in your browser. To exercise access, correction or deletion rights, write to ${email}.`)}</p></div></section></main><SiteFooter en={en}/><FloatingActions en={en}/><AnalyticsConsent en={en}/></>;}
